name: Slack post comment
description: Post comment on channel

inputs:
  channel:
    description: 'Channel'
    required: true
  message:
    description: 'Message text'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Make payload
      id: payload
      shell: bash
      run: |
        cat <<EOF > slack_result_comment.json
        { "channel":"${{ inputs.channel }}", "text": "${{ inputs.text }}" }
        EOF

    - name: Post to slack
      shell: bash
      run: |
        curl -s -X POST -H "Authorization: Bearer ${{ inputs.slack_bot_token }}" -H "Content-type: application/json" --data @slack_result_comment.json https://slack.com/api/chat.postMessage