name: Slack post message
description: Post a message on slack channel

inputs:
  channel:
    description: 'Channel'
    required: true
  text:
    description: 'Message'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get commit's info
      id: commit_info
      shell: bash
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
        echo "subject=$(git log -n 1 --pretty=format:%s)" >> $GITHUB_OUTPUT
        echo "author=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_OUTPUT
        echo "hash=$(git log -n 1 --pretty=format:%h)" >> $GITHUB_OUTPUT


    - name: Post to slack
      shell: bash
      run: |
        curl -s -X POST -H "Authorization: Bearer ${{ inputs.slack_bot_token }}" -H "Content-type: application/json" --data "{\"channel\":\"${{ inputs.channel }}\",\"text\":\"Starting build ${{ steps.commit_info.outputs.branch}} ${{ steps.commit_info.outputs.author}} ${{ steps.commit_info.outputs.hash}} ${{ steps.commit_info.outputs.subject}}\"}" https://slack.com/api/chat.postMessage