name: Free disk space
description: Frees disk space by removing unused files

runs:
  using: composite
  steps:
    - shell: bash
      run: df -h

    - name: Remove cached Docker images
      shell: bash
      run: sudo docker image prune --all --force

    - name: Remove Android toolkit
      shell: bash
      run: sudo rm -rf /usr/local/lib/android

    - name: Remove dotnet
      shell: bash
      run: sudo rm -rf /usr/share/dotnet
    
    - name: Remove CodeQL
      shell: bash
      run: sudo rm -rf /opt/hostedtoolcache/CodeQL

    - name: Remove GHC (Haskell)
      shell: bash
      run: sudo rm -rf /opt/ghc

    - shell: bash
      run: df -h