name: Pytype check
description: Check python types

runs:
  using: "composite"
  steps:
    - name: Run Pytype and save output
      run: bazel run //tools/pytype:run-checks 2>&1 | tee pytype_output.txt || true
      shell: bash

    - name: Summarize Pytype Results
      run: ./.github/actions/summarize_pytype_results.sh
      shell: bash