name: Cmms Codecov

on:
  push:
    branches:
      - main
      - 'releases/**'
      - '**'
    pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmms-codecov:
    name: Cmms Codecov
    runs-on: ubuntu-22.04
    env:
      CLUSTER_LOGS_PATH: cluster-logs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run tests
        run: bazel coverage --combined_report=lcov //...

      - name: Bazel output path
        run: echo "BAZEL_OUTPUT_PATH=$(bazel info output_path)" >> $GITHUB_ENV

      - name: Move coverage file
        run: mv ${{ env.BAZEL_OUTPUT_PATH }}/_coverage/_coverage_report.dat lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: bazel-sample-project/src-sample
