name: Create an Issue with cURL

on:
  workflow_dispatch:
    inputs:
      issue_title:
        description: 'Issue title'
        required: true
        default: 'Nuevo Issue desde cURL'

jobs:
  crear-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create issue using curl
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data '{
            "title": "${{ github.event.inputs.issue_title }}",
            "body": "Este issue fue creado directamente con una llamada a la API."
            }' \
          --fail