jobs:
  crear-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create issue using curl
        # 👇 Pasamos los inputs como variables de entorno al script
        env:
          ISSUE_TITLE: ${{ github.event.inputs.issue_title }}
          ISSUE_BODY: ${{ github.event.inputs.body_content }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          json_payload=$(printf '{"title": "%s", "body": "%s"}' "$ISSUE_TITLE" "$ISSUE_BODY")
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header "Authorization: Bearer $GITHUB_TOKEN" \
          --header "Content-Type: application/json" \
          --data "$json_payload" \
          --fail