name: Create an Issue
on:
  workflow_dispatch:
    inputs:
      issue_title:
        description: "Issue title"
        required: true
        default: ""
      body_content:
        description: "body content"
        required: false
        default: "Issue"

jobs:
  crear-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create issue using curl
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data '{
            "title": "${{ github.event.inputs.issue_title }}",
            "body": "${{ github.event.inputs.body_content }}",
            }' \
          --fail
