name: Pytype check

on:
  push:
    branches:
      - main
      - 'releases/**'
      - '**'
    pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytype-check:
    name: Pytype check
    runs-on: ubuntu-22.04
    env:
      CLUSTER_LOGS_PATH: cluster-logs
    steps:
      - name: Check out revision
        uses: actions/checkout@v4

      - name: Run Pytype and save output
        run: bazel run //:pytype-check 2>&1 | tee pytype_output.txt || true
        shell: bash

      - name: Summarize Pytype Results
        run: |
          echo "Total errors:"
          count=$(grep -c "error:" pytype_output.txt || echo 0)
          count=$(echo "$count" | head -n 1)
          echo "$count"

          echo ""
          echo "Error type:"
          grep -o "https://google.github.io/pytype/errors.html#[^ ]*" pytype_output.txt | sed 's/.*#//' | sort | uniq -c | sed 's/^[[:space:]]*//' || echo "None"

          echo ""
          echo "Files affected:"
          grep "error:" pytype_output.txt | cut -d':' -f1 | sort | uniq || echo "None"

          if [ "$count" -gt 0 ]; then
            echo "::error ::Pytype found $count errors"
            exit 1
          fi
        shell: bash